### ISSUE TITLE
Just a friendly notice

### ISSUE THREAD

**Issue by GMFalka** [Tom25/ipcam-timelapse#6]
Hello!

Thanks for writing those scripts! :)
All is working, but i had a bump launching make_timelapse.py that i fixed. Might others find this helpful

make_timelapse.py wasnt working on Ubuntu 18.10 with this error
```
 ./make_timelapse.py --today
Traceback (most recent call last):
  File "./make_timelapse.py", line 51, in <module>
    fourcc = cv2.cv.CV_FOURCC(*'XVID')
AttributeError: 'module' object has no attribute 'cv'
```

I changed this (in make_timelapse.py at line 51)
`fourcc = cv2.cv.CV_FOURCC(*'XVID')`
with this
`fourcc = cv2.VideoWriter_fourcc(*'XVID')`

**Comment by Tom25** [comment]
Thanks for the fix!

I think this may be an issue with newer versions of OpenCV (need to verify that), but glad this got it working for you. I might add this change to the `master` branch when I get a chance, assuming it doesn't break on prior versions of Ubuntu and/or OpenCV.

**Comment by Tom25** [comment]
This fix has been merged into the `master` branch. Thanks again!
